name: release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - name: Import GPG key
        id: import_gpg
        shell: bash
        run: |
          set -euo pipefail
          # Isolated keyring for this job
          export GNUPGHOME="$(mktemp -d)"
          chmod 700 "$GNUPGHOME"
          echo "GNUPGHOME=$GNUPGHOME" >> "$GITHUB_ENV"
          # Import ASCII-armored secret key from repo secret
          printf '%s' "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          # Output the primary fingerprint for later steps
          FPR="$(gpg --batch --list-secret-keys --with-colons | awk -F: '/^fpr:/{print $10; exit}')"
          echo "fingerprint=$FPR" >> "$GITHUB_OUTPUT"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
